In [44]:
import pandas as pd

In [45]:
lib_user = pd.read_csv(
    "/home/aca/Documents/S6_Lab/Projects/libraryDataAnalysis/cleaning/outputs/clean6_library_users.csv")
bk_issue = pd.read_csv(
    "/home/aca/Documents/S6_Lab/Projects/libraryDataAnalysis/cleaning/outputs/clean2_bookIssue.csv")
bk_details = pd.read_csv(
    "/home/aca/Documents/S6_Lab/Projects/libraryDataAnalysis/cleaning/outputs/clean1_bookDetails.csv")


# rename adm_no column to id for easy merging
bk_issue = bk_issue.rename({"adm_no": "id"}, axis=1)

# lib_user  # 2924 rows #id
# bk_issue # 41145 rows #id #acc_no
# bk_details #

In [46]:
# merge book details with book issue details on acc_no
bk_issue_bk_detials = pd.merge(bk_issue, bk_details, on="acc_no")

# Some rows are missing probably due to mismatch
# bk_issue_bk_detials.to_csv("bk_issue_bk_details.csv", index=False)

In [47]:
# merge lib user details with book issue details on id
bk_issue_lib_user = pd.merge(bk_issue, lib_user, on="id")

# bk_issue_lib_user.to_csv("bk_issue_lib_user.csv", index=False)

In [48]:
# Merge bk issue, bk details and lib user

bkIssue_libUser_bkDetails = pd.merge(bk_issue_bk_detials, lib_user, on="id")
# bkIssue_libUser_bkDetails

In [49]:
# checking if title_x and title_y are the same
for index, row in bkIssue_libUser_bkDetails.iterrows():
    if (row["title_x"] != row["title_y"]):
        raise Exception

In [50]:
# Drop redundant columns

# drop title_y
bkIssue_libUser_bkDetails.drop("title_y", axis=1, inplace=True)

In [51]:
bkIssue_libUser_bkDetails.rename(
    {
        "title_x": "title",
        "Sl No": "sl_no"
        }, axis=1, inplace=True)
bkIssue_libUser_bkDetails

,id,acc_no,title,issue_date,sl_no,author,publisher,sex,type,department,batch,checked_in(Y/N),book_issued(Y/N)
0,NT023,531,PRINCIPLES OF PHYSICAL CHEMISTRY,12/08/2016,530.0,PURI&SHARMA&PATHANIA,SHOBANLAL PUB,NaN,staff,NaN,NaN,N,Y
1,NT023,706,TEXT BOOK OF ORGANIC CHEMISTRY,01/08/2016,705.0,"TEWARI,KA&VISHNOI,N K&MEHROTRA,S N",VIKAS PUBLISHING HOUSE,NaN,staff,NaN,NaN,N,Y
2,NT023,831,PHYSICAL CHEMISTRY,12/08/2016,830.0,"CASTELLAN,GILBERT W",NAROSA PUBLISHING HOUSE,NaN,staff,NaN,NaN,N,Y
3,NT023,13478,HARRY POTTER AND THE HALF-BLOOD PRINCE,23/09/2016,13475.0,"ROWLING, J K",BLOOMSBURY,NaN,staff,NaN,NaN,N,Y
4,NT023,13498,SHERLOCK HOLMES SAMPOORNA KRUTHIKAL VOL.2,04/11/2016,13495.0,"CONAN DOYLE, SIR ARTHUR",D C BOOKS,NaN,staff,NaN,NaN,N,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
41083,20B671,7943,FUNDAMENTALS OF LOGIC DESIGN,04/03/2022,7941.0,"ROTH,CHARLES H",CENGAGE LEARNING INDIA PVT LTD.,NaN,student,ME,2020.0,N,Y
41084,20B818,18366,TEXTBOOK OF STRENGTH OF MATERIALS,18/03/2022,18359.0,"BANSAL,R K",LAXMI PUBLICATION,M,student,ME,2020.0,Y,Y
41085,457316,131,3000 SOLVED PROBLEMS IN PHYSICS,18/03/2021,131.0,"HALPERN,ALVIN",McGRAW-HILL,NaN,staff,MECHANICAL,NaN,N,Y
41086,457316,12772,ENGINEERING OPTIMIZATION,18/03/2021,12769.0,"RAVINDRAN,A & RAGSDELL,K M & REKLAITIS",WILEY INDIA,NaN,staff,MECHANICAL,NaN,N,Y
41087,457316,14740,ENGINEERING PHYSICS - PART I,18/03/2021,14737.0,"SELLADURAI,S",PHI,NaN,staff,MECHANICAL,NaN,N,Y

In [52]:
# Convert float to int

# convert sl_no 
bkIssue_libUser_bkDetails = bkIssue_libUser_bkDetails.astype(
    {
        "sl_no": "int"
        })

# convert batch. 
# NOTE: NaN values will be replaced by 0 
bkIssue_libUser_bkDetails["batch"] = bkIssue_libUser_bkDetails["batch"].fillna(0).astype(int)

# bkIssue_libUser_bkDetails.dtypes
# bkIssue_libUser_bkDetails

In [53]:
bkIssue_libUser_bkDetails

,id,acc_no,title,issue_date,sl_no,author,publisher,sex,type,department,batch,checked_in(Y/N),book_issued(Y/N)
0,NT023,531,PRINCIPLES OF PHYSICAL CHEMISTRY,12/08/2016,530,PURI&SHARMA&PATHANIA,SHOBANLAL PUB,NaN,staff,NaN,0,N,Y
1,NT023,706,TEXT BOOK OF ORGANIC CHEMISTRY,01/08/2016,705,"TEWARI,KA&VISHNOI,N K&MEHROTRA,S N",VIKAS PUBLISHING HOUSE,NaN,staff,NaN,0,N,Y
2,NT023,831,PHYSICAL CHEMISTRY,12/08/2016,830,"CASTELLAN,GILBERT W",NAROSA PUBLISHING HOUSE,NaN,staff,NaN,0,N,Y
3,NT023,13478,HARRY POTTER AND THE HALF-BLOOD PRINCE,23/09/2016,13475,"ROWLING, J K",BLOOMSBURY,NaN,staff,NaN,0,N,Y
4,NT023,13498,SHERLOCK HOLMES SAMPOORNA KRUTHIKAL VOL.2,04/11/2016,13495,"CONAN DOYLE, SIR ARTHUR",D C BOOKS,NaN,staff,NaN,0,N,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
41083,20B671,7943,FUNDAMENTALS OF LOGIC DESIGN,04/03/2022,7941,"ROTH,CHARLES H",CENGAGE LEARNING INDIA PVT LTD.,NaN,student,ME,2020,N,Y
41084,20B818,18366,TEXTBOOK OF STRENGTH OF MATERIALS,18/03/2022,18359,"BANSAL,R K",LAXMI PUBLICATION,M,student,ME,2020,Y,Y
41085,457316,131,3000 SOLVED PROBLEMS IN PHYSICS,18/03/2021,131,"HALPERN,ALVIN",McGRAW-HILL,NaN,staff,MECHANICAL,0,N,Y
41086,457316,12772,ENGINEERING OPTIMIZATION,18/03/2021,12769,"RAVINDRAN,A & RAGSDELL,K M & REKLAITIS",WILEY INDIA,NaN,staff,MECHANICAL,0,N,Y
41087,457316,14740,ENGINEERING PHYSICS - PART I,18/03/2021,14737,"SELLADURAI,S",PHI,NaN,staff,MECHANICAL,0,N,Y

In [54]:
# Write to csv
bkIssue_libUser_bkDetails.to_csv("temp.csv", index=False)

In [55]:
import csv

In [56]:
reader = csv.DictReader(open("temp.csv"))
fieldnames = ['id', 'acc_no', 'title', 'issue_date', 'sl_no', 'author', 'publisher',
              'sex', 'type', 'department', 'batch', 'checked_in(Y/N)', 'book_issued(Y/N)']

op = open("bkIssue_libUser_bkDetails.csv", "w")
writer = csv.DictWriter(op, fieldnames=fieldnames)
writer.writeheader()

for row in reader:
    _r = row
    if row["department"] == "CSE":
        _r['department'] = "CS"
    writer.writerow(_r)

In [57]:
op.close()

In [58]:
dff = pd.read_csv("bkIssue_libUser_bkDetails.csv")

dff.shape

(41088, 13)

In [59]:
dff['department'].unique()

array([nan, 'GENERAL', 'CS', 'IT', 'EC', 'ME', 'MECHANICAL',
       'INFORMATION TECHNOLOGY', 'COMPUTER SCIENCE', 'MTech CSE CL',
       'M.Tech  CSCL', 'EEE', 'M Tech  CSCL',
       'ELECTRONICS AND COMMUNICATION', 'Ph.D', 'PHYSICS', 'CE',
       'ECONOMICS', 'ELECTRICAL', 'M.Tech ME ROB', 'CENTRAL LIBRARY',
       'CIVIL', 'MATHEMATICS', 'MTech ME ROB', 'CHEMISTRY'], dtype=object)